### ISSUE TITLE
Incorrect en/decoding of recursive structure

### ISSUE THREAD

**Issue by krl** [dusk-network/kelvin#52] opened 2020-10-12 15:25 UTC
Regression found when porting the HAMT structure.

When encoding and decoding deeply nested structures, something goes wrong.

**Comment by ZER0** [comment] 2020-10-13 11:13
As reference, here one of the draft PR for fixing the issue:

https://github.com/dusk-network/canonical/pull/27

**Comment by krl** [comment] 2020-10-13 11:16
The other draft PR: #53

**Comment by ZER0** [comment] 2020-10-14 23:13
As discussed I pushed the MRE I found to test the failing encoding, the push are now in both `kelvin-integration` on `dusk-network/canonical` and `canon-integration` on `dusk-network/kelvin`. For the latter I couldn't use `un-unsafe` branch since it wasn't compiling at all, and therefore I couldn't run the tests.

**Comment by vlopes11** [comment] 2020-10-16 00:49
As a follow-up to the `narrow::regression_wtf` situation, the origin of the problem is the persist/restore operation 

The implementation is defined by `canonical_host::mem_store::MemStore::put`

The `MemStore` will receive an instance of `kelvin_hamt::NarrowHAMT`. This HAMT contains the correct mappings.

Below is the bytes representation on the `MemStore` of the states of the HAMT after every performed operation.

1. Initial -> `{2, 2, 2, 2}`
This is the representation of the `Handle::None` (leaf)

2. Push(17 => 80) -> `{2, 0, 17, 80, 2, 2}`
`2` - `Handle::None`
`0` -> `Handle::Leaf` indicates the next element is a mapping
`17, 80` -> element
`2, 2` -> `Handle::None`

3. Push(11 => 39) -> `{2, 1, 255, 25, 5, 64, 185, 241, 148, 175, 108, 174, 4, 97, 169, 214, 88, 129, 74, 210, 149, 180, 138, 169, 229, 9, 136, 233, 84, 208, 214, 194, 156, 234, 44, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2}`
`2` - `Handle::None`
`1` - `Handle::Node(_)`
`255` - Next element is a hash (not inline)
`25, 5, ... 234, 44` -> hash of the recursive node `H(H(17 => 80), H(11 => 39))`
`0, 0, 0, 0, 0, 0, 0, 2, 2, 2` -> need to understand, seems we should have only 2x `2` at the end instead of 3

4. Push(12 => 101) -> `{2, 1, 255, 25, 5, 64, 185, 241, 148, 175, 108, 174, 4, 97, 169, 214, 88, 129, 74, 210, 149, 180, 138, 169, 229, 9, 136, 233, 84, 208, 214, 194, 156, 234, 44, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2}`

Until the step 3, the representation is correct. The state correctly maps to the appended mappings.

As we can see, the step 4 won’t mutate the state. This way, the mapping `12 => 101` is not restored and the error occurs

**Comment by vlopes11** [comment] 2020-10-19 23:01
There is a confusion on the git branches.

The `kelvin-integration` was deleted from the canonical repo since it was merged to master.

But, this commit
https://github.com/dusk-network/canonical/commit/e46090c50032d0405c718cc84a9ba89ca53a6b8e
Changed the behavior of `ValMut` in a way it will no longer expect a closure.

However, the implementation of the HAMT on `canonical-integration` expects the closure to perform the nodes traverse. For example, here:
https://github.com/dusk-network/kelvin/blob/canonical-integration/structures/hamt/src/lib.rs#L119

Was this `e46090` commit on canonical correct?

**Comment by ZER0** [comment] 2020-10-21 10:55
Closing as wontfix since we're moving the development to [microkelvin](https://github.com/dusk-network/microkelvin/)

**Closed as completed by ZER0** 2020-10-21 10:55 UTC
Labels: status:wontfix
